# Generated by Django 3.0.8 on 2020-07-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dsuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=32, verbose_name='아이디')),
                ('useremail', models.EmailField(max_length=128, verbose_name='사용자이메일')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
            ],
            options={
                'verbose_name': 'DJANGOSTAGRAM 사용자',
                'verbose_name_plural': 'DJANGOSTAGRAM 사용자',
                'db_table': 'djangostagram_dsuser',
            },
        ),
    ]
