# Generated by Django 3.0.8 on 2020-07-17 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dsuser',
            old_name='useremail',
            new_name='email',
        ),
    ]
