# Generated by Django 3.0.8 on 2020-07-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imgurl',
            field=models.ImageField(max_length=128, upload_to='', verbose_name='이미지 주소'),
        ),
    ]
